/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tv.spring.doc.epub;

import org.jetbrains.annotations.NotNull;

public class App {

    public static void main(String[] args) {
        var options = new AppOptions();
        var baseUrl = getProjectUrl(options.getProject(), options.getSpringVersion());
        var doc = new SpringDocument(baseUrl);
        doc.build();
    }

    public static String getProjectUrl(@NotNull String projectName, @NotNull String version) {
        if (version.equals("latest")) {
            return String.format("https://docs.spring.io/%s/reference/", projectName);
        } else {
            return String.format("https://docs.spring.io/%s/reference/%s", projectName, version);
        }
    }
}
